-- CreateTable
CREATE TABLE "Application" (
    "id" TEXT NOT NULL PRIMARY KEY,
    "createdAt" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updatedAt" DATETIME NOT NULL,
    "status" TEXT NOT NULL DEFAULT 'Applied',
    "source" TEXT NOT NULL DEFAULT 'Other',
    "jobUrl" TEXT NOT NULL,
    "companyName" TEXT NOT NULL,
    "positionTitle" TEXT NOT NULL,
    "location" TEXT NOT NULL,
    "companyPhone" TEXT,
    "payMin" INTEGER,
    "payMax" INTEGER,
    "payPeriod" TEXT,
    "shift" TEXT,
    "hoursPerWeek" INTEGER,
    "jobType" TEXT,
    "workplace" TEXT,
    "datePosted" DATETIME,
    "dateApplied" DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "lastFollowedUpOn" DATETIME,
    "nextFollowUpOn" DATETIME,
    "contactName" TEXT,
    "contactEmail" TEXT,
    "jobDescription" TEXT,
    "resumeVersion" TEXT,
    "coverLetterVersion" TEXT,
    "notes" TEXT
);
